# Generated by Django 3.2.5 on 2021-09-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Dessert',
        ),
        migrations.AlterModelOptions(
            name='dessert',
            options={'ordering': ['created'], 'verbose_name': 'Postre', 'verbose_name_plural': 'Postres'},
        ),
    ]
